apiVersion: apps/v1
kind: Deployment 
metadata:
  name: artweb-deployment
  labels:
    app: artweb
    purpose: artweb-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: artweb
  template: 
    metadata:
      labels:
        app: artweb
    spec:
      containers:
        - name: artweb 
          image: rg.fr-par.scw.cloud/letsplay/artweb:develop.1.0
          envFrom:
          - configMapRef:
              name: prod-config

