# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 22:35
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=True, help_text="Coché si l'image doit être affichée sur le site", verbose_name='Est visible ?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('picture', models.ImageField(blank=True, upload_to='img', verbose_name='Photo')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'apparition")),
                ('is_background', models.BooleanField(default=False, help_text="Coché pour que l'image soit le fond de la barre de menu", verbose_name='Mis en fond de menu ?')),
                ('color', colorfield.fields.ColorField(default='#FFF', help_text="Couleur pour les textes affichés sur l'image", max_length=10, verbose_name='Couleur du texte')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ('order',),
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('carousel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Le nom sera affiché avant le carousel', max_length=255, null=True, verbose_name='Nom du carrousel')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'apparition")),
                ('is_visible', models.BooleanField(default=True, help_text='Coché si le carousel doit être affichée sur le site')),
            ],
            options={
                'verbose_name': 'Carrousel',
                'ordering': ('order',),
                'verbose_name_plural': 'Carrousels',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du menu (Accueil, Sculpture, Atelier...)', max_length=255, verbose_name='Nom du menu')),
                ('order', models.IntegerField(verbose_name="Ordre d'apparition")),
                ('parent', models.ForeignKey(blank=True, default=None, help_text='Menu dans lequel ce menu doit apparaître', null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.Menu')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=512, verbose_name='Texte')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'apparition")),
                ('is_visible', models.BooleanField(default=True, help_text='Coché si le texte doit être affiché sur le site', verbose_name='Est visible ?')),
                ('menu', models.ForeignKey(help_text='Texte à afficher dans le menu correspondant', on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='artwork.Menu')),
            ],
            options={
                'verbose_name': 'Texte',
                'ordering': ('order',),
                'verbose_name_plural': 'Textes',
            },
        ),
        migrations.AddField(
            model_name='carousel',
            name='menu',
            field=models.ForeignKey(help_text='Menu dans lequel sera affiché le carousel', on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='artwork.Menu'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='carousel',
            field=models.ForeignKey(blank=True, help_text="Carousel dans lequel l'image est affichée", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artwork.Carousel', verbose_name='Carrousel'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='menu',
            field=models.ForeignKey(blank=True, help_text="Menu dans lequel sera affiché l'image en dehors d'un caroussel", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artwork.Menu'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('name',)]),
        ),
    ]
