# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(verbose_name='Texte'),
        ),
    ]
