# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 12:14
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20160914_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FFF', help_text='Couleur de base du fond du site si cette image est en barre de menu', max_length=10, verbose_name='Couleur du fond'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='color',
            field=colorfield.fields.ColorField(default='#FFF', help_text="Couleur pour les textes affichés sur l'image", max_length=10, verbose_name='Couleur du texte du menu'),
        ),
    ]
