# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20161003_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='opacity',
            field=models.FloatField(default=1, help_text="Opacité de la couleur de fond d'écran - 1 = opaque, 0 = invisible"),
        ),
    ]
