# Generated by Django 2.0.7 on 2018-07-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artwork_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='carousel',
            field=models.ForeignKey(blank=True, help_text="Carousel dans lequel l'image est affichée", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artwork.Carousel', verbose_name='Carrousel'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='menu',
            field=models.ForeignKey(blank=True, help_text="Menu dans lequel sera affiché l'image en dehors d'un caroussel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artwork.Menu'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='menu',
            field=models.ForeignKey(help_text='Menu dans lequel sera affiché le carousel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousels', to='artwork.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='Menu dans lequel ce menu doit apparaître', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Menu'),
        ),
        migrations.AlterField(
            model_name='text',
            name='menu',
            field=models.ForeignKey(help_text='Texte à afficher dans le menu correspondant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='artwork.Menu'),
        ),
    ]
