# Generated by Django 2.0.7 on 2018-08-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20180731_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('conf_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.ImageField(blank=True, upload_to='img', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
