# Generated by Django 2.0.7 on 2019-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='color',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_background',
            field=models.BooleanField(default=False, help_text="Coché pour que l'image soit le fond de la barre de menu", verbose_name='Mis en fond ?'),
        ),
    ]
