# Generated by Django 2.0.7 on 2019-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_auto_20190314_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='picture',
            field=models.FileField(blank=True, upload_to='img', verbose_name='Photo'),
        ),
    ]
